# Site settings
title: 黑传说
email: gmail for jobinson99
description: "乌抵天明"
baseurl: ""
url: "http://jobinson.ga"

# Build settings
markdown: kramdown
permalink: pretty
relative_permalinks: true

future: true

# 分页


# 语法高亮
highlighter: pygments

# include:
# - .nojekyll

# 样式选择
themes: /themes/atlas

# 简化插入图片设置
img_url: /static/images


