name: 黑传说——乌抵天明
markdown: redcarpet
redcarpet:
    extensions: [tables, underline, strikethrough]
pygments: true

include:
- .nojekyll

# 样式选择
themes: /themes/atlas

# 简化插入图片设置
img_url: /static/images


